### PR TITLE
feat(plugin-react-refresh): rewrite to ts

### PR DESCRIPTION
**Pull request by Shinigami92**

### CODE REVIEW

**Comment by Shinigami92** [comment]
@aleclarson Can you now jump in to the code / my changes and especially look into the marked todos?

I currently just copied the `tsconfig.json` from `plugin-vue`
Also you can now run `yarn dev` and observe via this which further errors are currently there

Feel free to modify my branch and then write back to me when you are finished

**Comment by Shinigami92** [comment]
@aleclarson I currently don't know what `api-extractor` is doing, it's coming from the mono-root `package.json`
https://github.com/vitejs/vite/blob/a30724c8a492016a3f4fd1b209975b49e6972135/package.json#L25

**Review by aleclarson — APPROVED** [review]

**Comment by aleclarson** [comment]
@Shinigami92 Want to add yourself to `contributors` in pkg json?

**Comment by aleclarson** [comment]
I switched the build/dev scripts to use Vite and it's working great :) 

👉  https://github.com/aleclarson/vite/pull/1/commits/0fbad9f985613023379af47a43a3d491b2a2119c

@antfu I wonder if `plugin-vue` should do the same?

**Comment by Shinigami92** [comment]
> @Shinigami92 Want to add yourself to `contributors` in pkg json?

Cause I'm totally not involved in the React community but the TypeScript and/or Vue community, you would say "no thx" for now :slightly_smiling_face:

**Pull request merged**
